### ISSUE TITLE
Example not working like expected

### ISSUE THREAD

**Issue by developsessions** [zainkhan-afk/Differential-Drive-Robot-Navigation#1]
The PID works like expected but I have problems with the MPC. The simulation stuck and on the console I get this warning: `scipy/optimize/_optimize.py:353: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds`
What is wrong?

![canvas](https://user-images.githubusercontent.com/8073152/221887418-17b94d1e-a2bb-4721-bf23-d2710326b0d1.gif)

**Comment by zainkhan-afk** [comment]
Whenever you place a waypoint, the robot needs to drive over it to mark it as "reached" and then the next waypoint is selected as the robot's target. In this case the first waypoint is not being reached which means that the program does not update the goal of the robot. The MPC controller finds the best actions for a given set of waypoints called the horizon starting from the current goal waypoint, in this case the best actions result in the robot not going over the first waypoint. 
I am working on a solution now, I will update the repository by tomorrow, but in the meanwhile, a temporary workaround would be to place waypoints really close to one another like in the controller comparison script.

**Comment by find1dream** [comment]
Same problem, any update?

**Comment by zainkhan-afk** [comment]
Hi, the recent changes I pushed to main fixes this problem. The MPC implementation had some issues before, its all good now. Although, it still struggles at very sharp turns at times, I am working on a fix for that right now.
